version: '3.8'

services:
  php:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: symwords-php
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: symwords-nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/backend
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: postgres:16-alpine
    container_name: wordbe_db
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: wordbe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
